"""Write data/cache/evidence_review.md: one table per cached document, for eyeballing the evidence.

Usage: python scripts/dump_evidence.py
Bundled brochures come first, then any cached uploads.
"""

from __future__ import annotations

import sys
from pathlib import Path

from marsh import settings
from marsh.extraction import EXTRACTION_VERSION
from marsh.models import ExtractedDocument, load_json

OUTPUT_NAME = "evidence_review.md"


def _cell(value: str | None) -> str:
    return (value or "").replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def _labels(item) -> str:
    parts = []
    if item.row_label:
        parts.append(f"row: {item.row_label}")
    if item.column_label:
        parts.append(f"col: {item.column_label}")
    if item.footnote_markers:
        parts.append("markers: " + " ".join(item.footnote_markers))
    return "; ".join(parts)


def _load_all() -> list[ExtractedDocument]:
    docs = []
    for path in sorted(settings.CACHE_DIR.glob("*.json")):
        if path.name.startswith("matrix_"):
            continue
        try:
            docs.append(load_json(ExtractedDocument, path))
        except Exception as exc:  # noqa: BLE001 - skip non-evidence files
            print(f"skipping {path.name}: {exc}", file=sys.stderr)
    order = list(settings.BUNDLED_POLICY_FILES)
    return sorted(docs, key=lambda d: (order.index(d.document.document_id) if d.document.document_id in order
                                       else len(order), d.document.document_id))


def render(docs: list[ExtractedDocument]) -> str:
    lines = ["# Evidence review", "",
             "Generated by `scripts/dump_evidence.py` from `data/cache/`. Text is verbatim extracted text.", ""]
    for doc in docs:
        d = doc.document
        counts: dict[str, int] = {}
        for item in doc.evidence:
            counts[item.item_type.value] = counts.get(item.item_type.value, 0) + 1
        lines += [
            f"## {d.document_id} — {d.display_name}", "",
            f"- File: `{d.file_name}` · pages: {d.page_count} · sha256: `{d.sha256}`",
            f"- Extraction: {d.extraction_method.value} (docling {doc.docling_version}, extraction v{doc.extraction_version})"
            + (f" · full-page OCR on pages {doc.ocr_forced_pages}" if doc.ocr_forced_pages else ""),
            f"- Items: {len(doc.evidence)} — " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())),
            "",
            "| id | page | section | type | text | labels |",
            "|---|---|---|---|---|---|",
        ]
        for item in doc.evidence:
            lines.append(f"| {item.evidence_id} | {item.page} | {_cell(item.section)} | {item.item_type.value} "
                         f"| {_cell(item.text)} | {_cell(_labels(item))} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    docs = _load_all()
    stale = [d.document.document_id for d in docs if d.extraction_version != EXTRACTION_VERSION]
    if stale:
        print(f"warning: stale extraction version for {stale}; run scripts/extract_policies.py", file=sys.stderr)
    out: Path = settings.CACHE_DIR / OUTPUT_NAME
    out.write_text(render(docs), encoding="utf-8")
    print(f"wrote {out} ({len(docs)} documents, {sum(len(d.evidence) for d in docs)} items)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
