"""Write data/cache/evidence_review.md: one table per cached document, for eyeballing the evidence.

Usage: python scripts/dump_evidence.py
Shows the evidence as matching and audit will see it: annotated, with data/evidence_overrides.yaml
applied, rupee amounts displayed as ₹ (display_text; the stored text keeps the PDF's backtick).
Bundled brochures come first, then any cached uploads.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from marsh import settings
from marsh.evidence_store import EvidenceStore, display_label, display_text, load_evidence
from marsh.extraction import EXTRACTION_VERSION
from marsh.models import ExtractedDocument, ExtractionMethod, load_json

OUTPUT_NAME = "evidence_review.md"


def _cell(value: str | None) -> str:
    return (value or "").replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def _labels(item) -> str:
    parts = []
    if item.row_label:
        parts.append(f"row: {display_label(item.row_label, item.evidence_id)}")
    if item.column_label:
        parts.append(f"col: {display_label(item.column_label, item.evidence_id)}")
    if item.footnote_markers:
        parts.append("markers: " + " ".join(item.footnote_markers))
    return "; ".join(parts)


def _notes(item, store: EvidenceStore) -> str:
    notes = []
    if not item.citable:
        notes.append("NOT CITABLE")
    if item.evidence_id in store.overridden:
        notes.append("override")
    if item.extraction_method == ExtractionMethod.PYMUPDF_SUPPLEMENT:
        notes.append("supplement (text layer)")
    elif item.extraction_method == ExtractionMethod.DOCLING_FULL_PAGE_OCR:
        notes.append("OCR")
    return ", ".join(notes)


def _cache_files() -> list[Path]:
    return [p for p in sorted(settings.CACHE_DIR.glob("*.json")) if re.fullmatch(r"[0-9a-f]{64}\.json", p.name)]


def render(store: EvidenceStore, cached: dict[str, ExtractedDocument]) -> str:
    lines = ["# Evidence review", "",
             "Generated by `scripts/dump_evidence.py` from `data/cache/` with `data/evidence_overrides.yaml` applied.",
             "Text is the verbatim extracted text, shown with ₹ where the PDF renders the rupee sign as a backtick.",
             "Columns: tier = benefit tier; SI = si_condition; footnotes = linked footnote items.", ""]
    order = list(settings.BUNDLED_POLICY_FILES)
    for doc_id in sorted(store.documents, key=lambda d: (order.index(d) if d in order else len(order), d)):
        d = store.document(doc_id)
        doc = cached[doc_id]
        items = store.items_for_policy(doc_id, citable_only=False)
        counts: dict[str, int] = {}
        for item in items:
            counts[item.item_type.value] = counts.get(item.item_type.value, 0) + 1
        info = doc.annotation
        lines += [
            f"## {d.document_id} — {d.display_name}", "",
            f"- File: `{d.file_name}` · pages: {d.page_count} · sha256: `{d.sha256}`",
            f"- Extraction: {d.extraction_method.value} (docling {doc.docling_version}, extraction v{doc.extraction_version})"
            + (f" · full-page OCR on pages {doc.ocr_forced_pages}" if doc.ocr_forced_pages else ""),
            f"- Annotation: " + (f"v{info.version}, model {info.model}, variants {d.variants or 'none'}" if info
                                 else "not annotated"),
            f"- Items: {len(items)} ({sum(i.citable for i in items)} citable) — "
            + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())),
            "",
            "| id | page | section | type | text | labels | tier | variant | SI | footnotes | notes |",
            "|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        for item in items:
            lines.append(
                f"| {item.evidence_id} | {item.page} | {_cell(display_label(item.section, item.evidence_id))} "
                f"| {item.item_type.value} | {_cell(display_text(item))} | {_cell(_labels(item))} "
                f"| {item.benefit_tier.value} | {_cell(item.variant)} | {_cell(item.si_condition)} "
                f"| {' '.join(item.linked_footnote_ids)} | {_notes(item, store)} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    files = _cache_files()
    cached = {doc.document.document_id: doc for doc in (load_json(ExtractedDocument, p) for p in files)}
    stale = [d for d, doc in cached.items() if doc.extraction_version != EXTRACTION_VERSION]
    if stale:
        print(f"warning: stale extraction version for {stale}; run scripts/extract_policies.py", file=sys.stderr)
    store = load_evidence([p.stem for p in files])
    out: Path = settings.CACHE_DIR / OUTPUT_NAME
    out.write_text(render(store, cached), encoding="utf-8")
    total = sum(len(store.items_for_policy(d, citable_only=False)) for d in store.documents)
    print(f"wrote {out} ({len(store.documents)} documents, {total} items, {len(store.overridden)} overrides applied)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
